const mongoose = require('mongoose');

// Generic notification generated by the system when relevant events occur
// (connection request received, message received, job posted, event reminder, etc.)
const notificationSchema = new mongoose.Schema(
  {
    recipient: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    type: {
      type: String,
      enum: [
        'connection_request',
        'connection_accepted',
        'new_message',
        'new_job',
        'new_event',
        'post_comment',
        'post_like',
        'forum_reply',
        'system',
      ],
      required: true,
    },
    message: { type: String, required: true },
    link: { type: String, default: '' }, // frontend route to navigate to on click
    relatedId: { type: mongoose.Schema.Types.ObjectId }, // id of the related document
    isRead: { type: Boolean, default: false },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Notification', notificationSchema);
